version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/next/Dockerfile
    tty: true
    ports:
      - 80:3000
    volumes:
      - ./src:/app
    command: sh -c "npm run dev"
    restart: always
    environment:
      - WATCHPACK_POLLING=true

  firebase:
    build:
      context: .
      dockerfile: ./docker/firebase/Dockerfile
      args:
        WORKDIR: $WORKDIR
    tty: true
    ports:
      - "$FIREBASE_CLI_PORT:$FIREBASE_CLI_PORT"
      - "$FIREBASE_UI_PORT:$FIREBASE_UI_PORT"
      - "$FIREBASE_FUNCTIONS_PORT:$FIREBASE_FUNCTIONS_PORT"
    volumes:
      - ./firebase:/$WORKDIR
    restart: always
