import Head from 'next/head'
import { Header } from '../components/templates/Header'
import Top from '../components/views/Top'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Top />
      </main>

      <footer></footer>
    </div>
  )
}
